### ISSUE TITLE
Include arrays with common OID to string maps in common.js

### ISSUE THREAD

**Issue by rmhrisk** [GlobalSign/PKI.js#16]
For example something like this would help build UIs without applications having to know what each OID means:
              
algomap = {
                    "1.2.840.113549.2.1": "MD2",
                    "1.2.840.113549.1.1.2": "MD2 with RSA",
                    "1.2.840.113549.2.5": "MD5",
                    "1.2.840.113549.1.1.4": "MD5 with RSA",
                    "1.3.14.3.2.26": "SHA1",
                    "1.2.840.10040.4.3": "SHA1 with DSA",
                    "1.2.840.10045.4.1": "SHA1 with ECDSA",
                    "1.2.840.113549.1.1.5": "SHA1 with RSA",
                    "2.16.840.1.101.3.4.2.4": "SHA224",
                    "1.2.840.113549.1.1.14": "SHA224 with RSA",
                    "2.16.840.1.101.3.4.2.1": "SHA256",
                    "1.2.840.113549.1.1.11": "SHA256 with RSA",
                    "2.16.840.1.101.3.4.2.2": "SHA384",
                    "1.2.840.113549.1.1.12": "SHA384 with RSA",
                    "2.16.840.1.101.3.4.2.3": "SHA512",
                    "1.2.840.113549.1.1.13": "SHA512 with RSA"
                }; 

and

var typemap = {
                        "2.5.4.6": "C",
                        "2.5.4.10": "OU",
                        "2.5.4.11": "O",
                        "2.5.4.3": "CN",
                        "2.5.4.7": "L",
                        "2.5.4.8": "S",
                        "2.5.4.12": "T",
                        "2.5.4.42": "GN",
                        "2.5.4.43": "I",
                        "2.5.4.4": "SN"
                    },

**Comment by YuryStrozhevsky** [comment]
Done in v1.2.0
