### ISSUE TITLE
Include helper functions in common.js for common conversions

### ISSUE THREAD

**Issue by rmhrisk** [GlobalSign/PKI.js#17]
For example:
// function to convert certificate serial from buffer array if needed
            function toHexCodes(input_buffer) {
                var result = "";
                var int_buffer = new Uint8Array(input_buffer);
                
                for(var i = 0; i < int_buffer.length; i++){
                    var str = int_buffer[i].toString(16).toUpperCase();
                    result = result + ((str.length === 1) ? " 0" : " ") + str;
                }
                return result;
            };

            // function to convert string to b64
            function str2ab(str) {
                var buf = new ArrayBuffer(str.length*2); // 2 bytes for each char
                var bufView = new Uint8Array(buf);
                for (var i=0, strLen=str.length; i<strLen; i++) {
                    bufView[i] = str.charCodeAt(i);
                }
                return buf;
            };

**Comment by YuryStrozhevsky** [comment]
"toHexCodes" is in "common.js" from the very beginning - it has name "in_window.org.pkijs.bufferToHexCodes". In order to convert to/from BASE64 we can use "window.atob/btoa".
