### ISSUE TITLE
Change the region check method and add new region checks into cms_*.js files

### ISSUE THREAD

**Issue by davydsantos** [GlobalSign/PKI.js#26]
I was testing (node.js env) some alternatives to the region check method and came up with the function bellow:
```
	function createPackage(name) {
		var packageNames = name.split('.');
		var parent = in_window;
		var fullLoadedPackage = '';
		for (var i = 0; i<packageNames.length; i++) {
			if(typeof parent[packageNames[i]] === "undefined")
				parent[packageNames[i]] = {};
			else
			{
				if(typeof parent[packageNames[i]] !== "object") 
				{
					
					throw new Error("Name " + fullLoadedPackage + packageNames[i] + " already exists and it's not an object");
				}
			}
			parent = parent[packageNames[i]];
			fullLoadedPackage += packageNames[i] + '.';
		}
		return fullLoadedPackage.substr(0, fullLoadedPackage.length - 1);
	}
```
also add the checking of the x509 packages into those files (for node, it only worked after adding those packages):
* cms_simpl.js
```
	createPackage('org.pkijs.simpl.cms');
	createPackage('org.pkijs.simpl.x509');
```
* cms_schema.js
```
	createPackage('org.pkijs.schema.cms');
	createPackage('org.pkijs.schema.x509');
```

Also, a quick tip to import all the required libs (I've added common and asn1 into pkijs folders):
```
var extend = require("extend");

var pkijs_libs = [
  "pkijs/org/pkijs/common"
  ,"pkijs/org/pkijs/asn1"
  ,"pkijs/org/pkijs/x509_schema"
  ,"pkijs/org/pkijs/x509_simpl"
  ,"pkijs/org/pkijs/cms_schema"
  ,"pkijs/org/pkijs/cms_simpl"
];


// #region Merging function/object declarations for ASN1js and PKIjs
var pkijs = {};
for (var i = 0, len = pkijs_libs.length; i < len; i++) {
  extend(true, pkijs, require(pkijs_libs[i]));
};
// #endregion
```

**Comment by YuryStrozhevsky** [comment]
Main idea of PKIjs code is making a code "transparent" to any evironment. In PKIjs there are no code worring about Node.js, any package manager or whatever. Instead of it each developer using PKIjs need to worry about the eviromnent he/she is using. 

As a conclusion: I do not recommend to include information about Node.js in PKIjs files. Instead you should import PKIjs object from Node.js files, as it shown in README. Regarding your code with require("extend"): it was long time ago and I do not remember all things, but I had problems with "extend" package and do recommend to use "node.extend".

**Comment by davydsantos** [comment]
I understand that you don't want to add any dependency or relation to node.js. But the idea of the createPackage function was only to try to extract a repeated task into a method and call it in a more readable way.

Still, I'm having problems running the test app (main idea is to create a P7S Viewer). But when I try to read the P7S I get some wired error (even thought that the same signed file works if I use the CMS Signed Copmlex example. I'm debugging to check what's wrong with my code (even having in mind that it has less than 10 lines) and with the use of PKIjs on a Node.js env.

**Comment by YuryStrozhevsky** [comment]
Try to use "node.extend" instead of "extend" - its might help you.

**Comment by davydsantos** [comment]
I have even put all the content into a single file but it didn't help.

**Comment by YuryStrozhevsky** [comment]
Try to local in code line with "Wrong parameter: input_buffer has zero length" and put any additional debug messages there.

Since this is not a PKIjs bug and I have no plans to change "cms_*.js" I have closed the issue.
