### ISSUE TITLE
Experimental PDF signing

### ISSUE THREAD

**Issue by Setasign** [GlobalSign/PKI.js#33]
As promised (@YuryStrozhevsky, @rmhrisk) I just prepared some things based on jsPDF: 

- A simple [plugin](https://github.com/Setasign/jsPDF/blob/PKI.js-integration/jspdf.plugin.acroform.js) for jsPDF which allows you to create signature fields.
- A simple [signature plugin](https://github.com/Setasign/jsPDF/blob/PKI.js-integration/jspdf.plugin.sign.js) which simply misses the magic of PKIjs to create the CMS signature.

I had to make some more changes to the main jsPDF in view to dynamic object number generation but after all it should work as an experimental basis for you.

The fork/branch is available: https://github.com/Setasign/jsPDF/tree/PKI.js-integration 

If you have any question or need further support, feel free to contact me/us!

Cheers,
Jan

**Comment by YuryStrozhevsky** [comment]
Hello Jan!

Really impressed with your effort on integration between jsPDF and PKIjs!
Do appreciate this and hope I will create a pull request to your repositiry with full-featured code for PDF signing.


Thank you very much!
Yury Strozhevsky

**Comment by YuryStrozhevsky** [comment]
Seems that it is impossible to combine Setasign plugin having "sync code" with "async nature" of PKIjs. Another solution for PDF signing is comming soon.

**Comment by sentiasa** [comment]
@YuryStrozhevsky any news for PDF signing?

**Comment by rmhrisk** [comment]
@sentiasa we have signing and verification working, we will ultimately release another set of libraries that we use to do this but we have no planned release date at this time. Feel free to contact me at ryan @ peculiarventures dot com if you want to share your interest in this capability, it could influence what and how we do any release in the future.

**Comment by NoahCardoza** [comment]
Any update on this?

**Comment by YuryStrozhevsky** [comment]
[Hancock](http://hancock.ink)

For this service I made a specialized client JS library working with any PDFs and having ability to sign and verify. And many more. As for public release for the library: not planned for the moment, AFAIK.

**Comment by typoworx-de** [comment]
> As promised (@YuryStrozhevsky, @rmhrisk) I just prepared some things based on jsPDF:
> The fork/branch is available: https://github.com/Setasign/jsPDF/tree/PKI.js-integration

@setasign why has the branch been deleted?
