### ISSUE TITLE
Load private key from file system

### ISSUE THREAD

**Issue by BaurzhanSakhariev** [GlobalSign/PKI.js#34]
As far as I know Web Crypto API allows usage of local private keys (.p12 of pkcs#12-formatted files). But in the examples page I found only generate-key-on-the-fly or read-binary-.cer methods. Does PKI.js support loading local .p12 file?

Thanks!

**Comment by YuryStrozhevsky** [comment]
In Web Cryptography API there are functions for importing/exporting keys from "spki" (public keys) and "pkcs8" (private keys) format. PKCS#12 format is a special format to convey encrypted data about certificate and private key. There is no support for PKCS#12 in Web Crypto. But it is possible to create special "helper" to work with PKCS#12 files. It would be implemented in PKIjs but this task not not so important for PKIjs library development at the moment. Meanwhile you can use importing/exporting private keys into "pkcs8" format. How to use it was shown in [this example](https://github.com/GlobalSign/PKI.js/tree/master/examples/How%20To%20Encrypt%20CMS%20via%20certificate).

**Comment by BaurzhanSakhariev** [comment]
Thank you for the fast response!
If I got you properly, I can implement pkcs#12 "helper" in pure JS, am I right? Do you mean by implementing "helper" a lot of boilerplate .p12-file parsing JS-code or you mean using special "native" tool like openssl and calling executable from JS via ActiveX and further handle converted file with JS?

**Comment by YuryStrozhevsky** [comment]
I mean "a lot of boilerplate .p12-file parsing JS-code". Inside PKIjs such "helpers" are inside "*_simpl.js" files, take a look. As I said support for PKCS#12 would be allso a part of PKIjs, but its not in our nearest plans.

**Comment by BaurzhanSakhariev** [comment]
Thanks!

**Comment by danieldeschamps** [comment]
I'm also very interested also in parsing pkcs#12!

**Comment by YuryStrozhevsky** [comment]
I believe I will find a time to implement the PKCS#12 soon.

**Comment by danieldeschamps** [comment]
Nice ;)

**Comment by YuryStrozhevsky** [comment]
Now we have PKCS#12 in latest release. Unfortunally PKIjs uses modern crypto algorithms and Windows uses very old algorithms. That is why our version of PKCS#12 data could not be read via standard Windows GUI. But OpenSSL is able to work with some of our output formats with option "-nomacver".
