### ISSUE TITLE
Possible to add custom attributes in a PKCS10 csr?

### ISSUE THREAD

**Issue by brice-nandi** [GlobalSign/PKI.js#35]
Hello,

Is it possible to add a custom attribute named "CertificateTemplate" in a csr before signing?
It would be so that a Microsoft PKI would agree to create a certificate..
If it is possible, could you show me how?

Thanks in advance for your answer,

**Comment by YuryStrozhevsky** [comment]
You can append any attribute you want. Here is [source code of example](https://github.com/GlobalSign/PKI.js/tree/master/examples/PKCS%2310%20complex%20example). Here is [live example](https://pkijs.org/examples/PKCS10_complex_example.html).

**Comment by brice-nandi** [comment]
Yes,

But but the value of the field 'type' has to be an OID right?
You can't just pass the 'name' of the attribute as a parameter.
Am I wrong?

**Comment by YuryStrozhevsky** [comment]
Yes, CSR standard (PKCS#10) and PKIjs supports OIDs only. You must find neccessary OID for your specific attribute, then find which type has a value for this attribute, then make PKIjs attribute and then append it to PKIjs CSR before signing.

**Comment by brice-nandi** [comment]
Thank you for your answer,

Sorry, I'm pretty new to this, so I don't fully understand..
Let's say I have a custom OID '1.3.1.4.1.311.21.7'. (Certificate template)
How do I find which type has a value for this attribute?

**Comment by YuryStrozhevsky** [comment]
Find this info in that document where you found this OID :) Seems that this OID is not "well-known" and probably it has a "private formatiing".

**Comment by brice-nandi** [comment]
OK, thanks for all the information. :)

**Comment by brice-nandi** [comment]
Sorry,

Last question, is it possible to set an extension for a csr?

**Comment by YuryStrozhevsky** [comment]
Yes, everything is possible. In PKCS#10 PKIjs examples there are no extensions, but in fact you can use [code from other example](https://github.com/GlobalSign/PKI.js/tree/master/examples/Certificate%20complex%20example). There you will find how to append any extensions.

**Comment by brice-nandi** [comment]
Thanks again.

**Comment by rmhrisk** [comment]
@YuryStrozhevsky added extensions to the sample for p10 - https://pkijs.org/examples/PKCS10_complex_example.html

**Comment by brice-nandi** [comment]
Yes,

Thank you, Yury already notified me.

Brice Nandi
*Deployment Engineer @ *
* revevol*
Revevol France SAS
mobile: +33 6.16.65.09.01

2015-05-18 21:25 GMT+02:00 Ryan Hurst <notifications@github.com>:
