### ISSUE TITLE
Encapsulate a Sequence in an OCTETSTRING?

### ISSUE THREAD

**Issue by brice-nandi** [GlobalSign/PKI.js#37]
Is there a simple way to encapsulate a ASN1 SEQUENCE in a OCTETSTRING in a PKCS10 csr?

I'm actually creating a PKCS10 csr from scratch.

Thanks in advance,

**Comment by YuryStrozhevsky** [comment]
```javascript
var seq = new org.pkijs.asn1.SEQUENCE();
var octetString = new org.pkijs.asn1.OCTETSTRING({ value_hex: seq.toBER(false) });
```

Brice, this is not a "support board". This site section intended to be a list of issues which customers have during work with PKIjs. Please ask your question in e-mail. My e-mail exists in my GitHub profile.
