### ISSUE TITLE
pkijs.org.pkijs.getAlgorithmParameters missing from npm module

### ISSUE THREAD

**Issue by mikemaccana** [GlobalSign/PKI.js#41]
I'm trying to get pkijs working, in the browser, using the npm module and the custom instructions needed to load pkijs:

    // See https://www.npmjs.com/package/pkijs
    var merge = require("node.extend");
    var common = require("asn1js/org/pkijs/common");
    var _asn1js = require("asn1js");
    var _pkijs = require("pkijs");
    var _x509schema = require("pkijs/org/pkijs/x509_schema");
    // #region Merging function/object declarations for ASN1js and PKIjs
    var asn1js = merge(true, _asn1js, common);
    var x509schema = merge(true, _x509schema, asn1js);
    var pkijs_1 = merge(true, _pkijs, asn1js);
    var pkijs = merge(true, pkijs_1, x509schema);

pkijs.org.pkijs exists, however pkijs.org.pkijs.getAlgorithmParameters is missing. 

It looks like `getAlgorithmParameters` itself is missing from `./node_modules/asn1js/org/pkijs/common.js`. Whereas `https://pkijs.org/examples/org/pkijs/common.js` includes it. 

Perhaps this was from back in the day when only node used npm?

**Comment by YuryStrozhevsky** [comment]
Hello Mike!
Yes, the version in NPM module is quite old. I do not use server-side for a while (about an year). So, you can simply copy all latest PKIjs and ASN1js files in module directory on server. And I promise you that when I will have a time I will fix the issue with old code for NPM modules.

**Comment by mikemaccana** [comment]
Ah, is it difficult to `npm publish` the current code? I imagine this will catch a few people.

**Comment by mikemaccana** [comment]
Keep in mind this is for the browser - npm is by far the most popular browser side package manager these days.

**Comment by YuryStrozhevsky** [comment]
Ok, done.

**Comment by mikemaccana** [comment]
Thanks Yuri! 👍

**Comment by YuryStrozhevsky** [comment]
Thank you Mike to remind me about NPM ;)
