### ISSUE TITLE
Add support for smartcards

### ISSUE THREAD

**Issue by atallo** [GlobalSign/PKI.js#44]
I don't know if  browser/WebCrypto supports necessary, but... can you add support to smartcards in PKI.js?

Thanks

**Comment by YuryStrozhevsky** [comment]
PKIjs works via Web Cryptography API. Web Cryptography API works with client-side JavaScript. The client-side JavaScript has no access to physical devices. So, it is impossible to add support for smartcards (or any other hardware tokens) in PKIjs. However, it is possible to create a Node.js library with such functionality and use a kind of "polyfill" for making remote requests. At the moment we are working on it, please watch on new repositories under (https://github.com/PeculiarVentures)[https://github.com/PeculiarVentures].

**Comment by atallo** [comment]
Sorry I see an old Draft with smartcard support: https://www.w3.org/community/webcryptoapi/draft/

I can't work with keys generated by the application itself, 

In future... http://www.w3.org/TR/webcrypto-key-discovery/ can be a good solution and forget current Java applets.

Thanks!

**Comment by rmhrisk** [comment]
Key discovery is unlikley to get implemented and really only would work for pre-generated keys. One could in theory use the https://developer.chrome.com/apps/app_usb interface from a chrome extension to talk to a USB based smart card but would need to redevelop the minidriver and PC/SC components in JS which is totally doable but also a non-trivial amount of work. Instead I recommend doing a derived credential in the browser, for example imagine a server setup to do mutual ssl, uponce succesfull authentication it could issue a bearer token. That bearer token could be used to issue a in-browser session certificate. That can be used to do certificate things in-browser. This translates the client certificate into something short-lived and usable within the session.

**Comment by billbarni** [comment]
I don't think some of you get the idea of what smarcard support means. It does not mean access to read the USB device, but to request the browser to do so. You can see a printscreen of the browser asking for the user to select what certificate stored in a smartcard he wants to use to access a specific website here:

https://stackoverflow.com/questions/47942288/request-client-certificate-on-javascript

**Comment by rmhrisk** [comment]
The browser does not let websites interact with things outside of the browser.

Smartcards and local certificates are outside of the browser.

It is not possible to do what you want from JavaScript without the addition of middleware that adds this capability.

See https://fortofyapp.com for our answer to this.
