### ISSUE TITLE
Whats is a CA bundle file?

### ISSUE THREAD

**Issue by ricardocunha** [GlobalSign/PKI.js#45]
Whats is a CA bundle file?

What format is acceptable?

**Comment by rmhrisk** [comment]
Just a text file with PEM blocks of certificates, similar to what apache would expect. Here is a tool that creates them based off different trust stores - https://github.com/PeculiarVentures/tl-create/  also see: https://github.com/GlobalSign/PKI.js/tree/master/examples/CA%20bundle
