### ISSUE TITLE
webpack support

### ISSUE THREAD

**Issue by rapropos** [GlobalSign/PKI.js#47]
It would be nice if all the parts of asn1js/pkijs could be used easily with the webpack module loader. Currently I am having to manually splice together asn1/common, asn1, pki/x509_simpl, and pki/x509_schema into one giant file, which is not particularly sustainable. I see the documentation about using node.extend to solve what appears to be a similar problem when running on Node.js, but I don't think that technique would work with webpack.

**Comment by YuryStrozhevsky** [comment]
The PKIjs was designed to be an independant library as much as it is possible. So, we do not have any code, specific to any "package manager". Also we do not have a plans to support (directly) any package manager. Instead of it we suggested a way how to use it in Node.js applications. You can change the code we suggested in order to match your specific requirements.

**Comment by rapropos** [comment]
Would you consider changing references to `in_window` within `org.pkijs.getCrypto` and `org.pkijs.getRandomValues` to refer directly to `window` instead, then? As you document, those methods aren't going to work in a Node.js environment anyway, but as things stand, they won't work in a webpack environment either even though there actually is environmental support in the true `window`, because the main `in_window` argument to the module is an exports sandbox.

**Comment by YuryStrozhevsky** [comment]
Yes, it could be a case. I will think how to handle it correctly.

**Comment by YuryStrozhevsky** [comment]
In today's code I have introduced a way how to use "crypot engines" with PKIjs. As a consiquence the code will satisfy also your request, please take a look at the code.

**Comment by rapropos** [comment]
Great, thank you very much for your assistance.
