### ISSUE TITLE
Can't get Inter-module references work in NodeJS

### ISSUE THREAD

**Issue by veselov** [GlobalSign/PKI.js#49]
Hi.

I'm not sure if I'm doing something wrong, or this really should be documented.

Often times, one PKIJS module uses another (i.e. cms_simpl uses x509_simpl). To access the other module, 'in_window' object is used, which is passed in to the closure function when module is initialized. For Node, it's 'module.exports' object.

If I called `x509 = require('pkijs/org/pkijs/x509_simpl')`, NodeJS will create a new module object, and `x509_simpl` will attach its implementation to its `export` property. When I later call `cms = require('pkijs/org/pkijs/cms_simpl')`, a new module object is created, and `cms_simpl` will attach itself to that module's `export` property. Now, the contents of an `export` property is what returned from `require()` call.

I can, of course, merge results of `require()` calls together (i.e. with node.extend). But the reference to the original export property is "stuck" in the corresponding module implementation, and there is no way to influence this for the loaded modules code, because that reference is accessed using scope, not object property.

The good news, is that the code always looks up properties chain from the `in_window`, starting from org. Those can be easily overwritten, forcing the module to "use" newer version of it, if provided. So, I ended up having this as a loading code for PKIJS module:

```
    var PKI;

    (function() {
        let asn1js = require('asn1js');
        let asn1common = require('asn1js/org/pkijs/common');
        let pkijs = require('pkijs');
        let x509Schema = require('pkijs/org/pkijs/x509_schema');
        let cmsSchema = require('pkijs/org/pkijs/cms_schema');
        let cmsSimple = require('pkijs/org/pkijs/cms_simpl');
        let x509Simple = require('pkijs/org/pkijs/x509_simpl');

        // merge them togther

        let merger = merge(true, asn1js, asn1common);
        merger = merge(true, merger, pkijs);
        merger = merge(true, merger, x509Schema);
        merger = merge(true, merger, cmsSchema);
        merger = merge(true, merger, cmsSimple);
        merger = merge(true, merger, x509Simple);

        asn1js.org = merger.org;
        asn1common.org = merger.org;
        pkijs.org = merger.org;
        x509Schema.org = merger.org;
        cmsSchema.org = merger.org;
        cmsSimple.org = merger.org;
        x509Simple.org = merger.org;

        PKI = merger;

    })();
```

So far, seems to be working fine :)

**Comment by YuryStrozhevsky** [comment]
Yes, also a good way to go. I will test it later and probably will update README.
