### ISSUE TITLE
Need to create a sample dynamically loading mozilla trusted cert list

### ISSUE THREAD

**Issue by rmhrisk** [GlobalSign/PKI.js#5]
All applications will need a list of trusted certificates we need to do a sample of dynamically loading the mozilla trusted roots based on this file: http://mxr.mozilla.org/mozilla/source/security/nss/lib/ckfw/builtins/certdata.txt

**Comment by YuryStrozhevsky** [comment]
Done in scope of "X.509 certificate complex example"
