### ISSUE TITLE
qcStatement

### ISSUE THREAD

**Issue by iferreiro** [GlobalSign/PKI.js#54]
Hello. I was trying to add the extension "QCStatement" to a request (CSR). The problem occurs when I try to add a custom value.
I need to add the extension QCStatement v2 (OID: 1.3.6.1.5.5.7.1.3) with a custom value such as (1.2.3.4).

Please any help will be appreciated

**Comment by YuryStrozhevsky** [comment]
Probably [this already closed issue](https://github.com/GlobalSign/PKI.js/issues/50) would help you.

**Comment by rmhrisk** [comment]
@iferreiro I am interested in seeing the QC stuff getting added eventually please provide a PR when your done.

**Comment by iferreiro** [comment]
@YuryStrozhevsky 
Hi, sorry for the delay. I tried what you sent but I failed to get the desired result. The asn1 coding should be as follows:

SEQUENCE (2 elem)
   OBJECT IDENTIFIER1.3.6.1.5.5.7.1.3
   OCTET STRING (1 elem)
      SEQUENCE (1 elem)
         SEQUENCE (2 elem)
             OBJECT IDENTIFIER1.3.6.1.5.5.7.11.2
             SEQUENCE (1 elem)
                  OBJECT IDENTIFIER2.16.32.1.10.1


Also, I attach a certificate that has the QCStatement coded correctly and is as I need.

**Comment by YuryStrozhevsky** [comment]
The link I sent is only an example how to work with PKCS#10 extensions (CSR extensions). This is not an exact code making QC.

**Comment by iferreiro** [comment]
Okey, thank you Yury. Do you know is there any way by which I can create the structure that I indicated in the previous comment?


**I'm close to getting the result.**

new org.pkijs.simpl.EXTENSION({
           extnID: "1.3.6.1.5.5.7.1.3",
           critical: false,
           extnValue: (new org.pkijs.asn1.OID({ value: "1.3.6.1.5.5.7.11.2" })).toBER(false)
    })

SEQUENCE (2 elem)
   OBJECT IDENTIFIER 1.3.6.1.5.5.7.1.3
   OCTET STRING (1 elem)
      SEQUENCE (1 elem)
         SEQUENCE (2 elem)
             OBJECT IDENTIFIER 1.3.6.1.5.5.7.11.2
             SEQUENCE (1 elem)
                  **OBJECT IDENTIFIER 2.16.32.1.10.1** (I need to add this somehow)

**Comment by YuryStrozhevsky** [comment]
I still can not get what do you expect from me? You need *me* to create exact code for *you*?

**Comment by iferreiro** [comment]
Not at all, maybe I wrote wrong. I already solved the problem, what I need is to know if there is a way to create for example a sequence with a sequence and a oid inside. And then if I can put that sequence inside an extension..

**Comment by YuryStrozhevsky** [comment]
Sure, of course it is possible:
```javascript
            var sequenceWithOID = new org.pkijs.asn1.SEQUENCE({
                value: [
                    new org.pkijs.asn1.SEQUENCE({
                        value: [
                            new org.pkijs.asn1.OID({ value: "1.1.1.1" })
                        ]
                    })
                ]
            });
```
Then you can put it inside extensions array:
```javascript
                        extensions.extensions_array.push(new org.pkijs.simpl.EXTENSION({
                            extnID: "2.2.2.2",
                            critical: false,
                            extnValue: sequenceWithOID.toBER(false)
                        }));
```
