### ISSUE TITLE
Extension in hexadecimal

### ISSUE THREAD

**Issue by charlesvane** [GlobalSign/PKI.js#55]
Hello. I wanted to know if there is a possibility to pass a hexadecimal value to a function and that it encodes the appropriate extension.

**Comment by YuryStrozhevsky** [comment]
Sure, this is possible:
```javascript
            cert_simpl.extensions.push(new org.pkijs.simpl.EXTENSION({
                extnID: "2.2.2.2",
                critical: false,
                extnValue: hexadecimalBuffer // MUST BE AN ARRAYBUFFER TYPE
            }));
```
As for complex example of making certificates (and extensions) see [this link](https://github.com/GlobalSign/PKI.js/tree/master/examples/Certificate%20complex%20example).
