### ISSUE TITLE
Sequence with 2 values

### ISSUE THREAD

**Issue by charlesvane** [GlobalSign/PKI.js#56]
Hi. There any way to put 2 values in a sequence or any extension?

For example, something like that?

extnValue: (new org.pkijs.asn1.SEQUENCE({
                                        values: [
                                            new org.pkijs.asn1.OID({ value: "1.2.3.4" }).toBER(false),
                                            new org.pkijs.asn1.OID({ value: "1.2.3.5" }).toBER(false)
                                        ]
                                    }))

**Comment by YuryStrozhevsky** [comment]
Working with ASN.1 structures inside PKIjs handled via [ASN1js library](https://github.com/GlobalSign/ASN1.js). There are many examples of ASN1js usage in README.
