### ISSUE TITLE
Provide an example of signing & verifing an image like produced by signature-pad

### ISSUE THREAD

**Issue by rmhrisk** [GlobalSign/PKI.js#6]
Signing and verifying a signature is a very common case, providing an example of doing this using https://github.com/thomasjbradley/signature-pad or https://github.com/szimek/signature_pad would be useful.

**Comment by rmhrisk** [comment]
Nice to have but someone can figure out, has less to do with PKIjs and more to do with PDFs

**Comment by zigasaletinger** [comment]
Hey, great work on the lib!

Having PDF support would be really awesome! There should be a way to "crowdsource" / found enhancement requests, I bet PDF support is needed by many :)

**Comment by YuryStrozhevsky** [comment]
We already have PDF support lib (signing/verification and encryption/decryption) and the lib is going to be published very soon. But most likely the lib would be licensed under "only for non-comersial usage" rules. See news for [PV repo](https://github.com/PeculiarVentures).

**Comment by zigasaletinger** [comment]
thanks lettning me know, [found it](https://github.com/PeculiarVentures/js-zxing-pdf417)

**Comment by YuryStrozhevsky** [comment]
The PDF support lib is not based on "js-zxing-pdf417", it is a separate library with no "external dependencies".

**Comment by thr0w** [comment]
+1 for PDF signing sample

**Comment by rmhrisk** [comment]
Closing as this is overly specific sample, better to track PDF signing sample separately.
