### ISSUE TITLE
PKCS#12 inconsistent naming

### ISSUE THREAD

**Issue by peterlacko** [GlobalSign/PKI.js#61]
Function [in_window.org.pkijs.simpl.PFX.prototype.fromSchema](https://github.com/GlobalSign/PKI.js/blob/master/org/pkijs/pkcs12_simpl.js#L294) from `pkcs12_simpl.js` tries to create schema by calling `in_window.org.pkijs.schema.PFX()`, but in [pkcs12_schema.js](https://github.com/GlobalSign/PKI.js/blob/master/org/pkijs/pkcs12_schema.js#L150) it is named as `in_window.org.pkijs.schema.PKCS12`. Also in [PKCS12SimpleExample.html](https://github.com/GlobalSign/PKI.js/blob/master/examples/PKCS12%20Simple%20Example/PKCS12SimpleExample.html#L897) `PKCS12` object is created calling `new org.pkijs.simpl.PKCS12()` instead of `new org.pkijs.simpl.PFX()`. Problem can be simply fixed by correct renaming, I'm not sure though, what naming is correct so creating issue instead of PR.

**Comment by YuryStrozhevsky** [comment]
Yes, seems that I changed naming in [this fix](https://github.com/GlobalSign/PKI.js/commit/177ccfe1db3efbe5333011ca7403a1b0f2290d04), but not completelly.
Thank you I will correct the code at Monday.

**Comment by YuryStrozhevsky** [comment]
Fixed in [latest commit](https://github.com/GlobalSign/PKI.js/commit/594d549afd1643851ca53e971ac562eaec6501e6).
