### ISSUE TITLE
Incorrect logic in CMS_SIGNED_DATA verify function

### ISSUE THREAD

**Issue by peterlacko** [GlobalSign/PKI.js#65]
Looks like there is a bug in [org.pkijs.simpl.CMS_SIGNED_DATA.prototype.verify](https://github.com/GlobalSign/PKI.js/blob/master/org/pkijs/cms_simpl.js#L1795), where `checkCA` function is evaluated already when building a `checkCA_promises` list, i.e. before execution of sequence chain. This results into empty `signer_cert` object in `checkCA` function and thus to a failure or incorrect condition evaluation inside the function. I guess it's not intended behaviour?

**Comment by YuryStrozhevsky** [comment]
In fact you are right, could be the case. I have fixed it in latest commit.
