### ISSUE TITLE
Examples not working - Dont find "org.pkijs.simpl.PKCS10"

### ISSUE THREAD

**Issue by Manuelp443** [GlobalSign/PKI.js#69]
The examples are not working. 

Example: PKCS#10
Because it dont find "org.pkijs.simpl.PKCS10();"

Picture see Attachment
![example](https://cloud.githubusercontent.com/assets/20996300/17631970/7aa8f280-60c6-11e6-98d1-54101d24b682.png)

I think there is the "pkcs10_simpl.js" missing.

**Comment by YuryStrozhevsky** [comment]
Please check [this link](https://pkijs.org/examples/PKCS10_complex_example.html). For me all is working pretty well.

**Comment by rmhrisk** [comment]
Please see: https://github.com/PeculiarVentures/PKI.js/issues/70
