### ISSUE TITLE
PKCS#10 complex example - dont show in browsers

### ISSUE THREAD

**Issue by Manuelp443** [GlobalSign/PKI.js#70]
Affected browsers: IE, Chrome, Firefox 

They have a problem with the "#" in the directoryname. 

Please delete it. :)

**Comment by YuryStrozhevsky** [comment]
This code is only an example. If you wish you could create your own directory structure for your real environment.

**Comment by rmhrisk** [comment]
@Manuelp443 

I just downloaded: https://github.com/PeculiarVentures/PKI.js/archive/master.zip

And then downloaded: https://github.com/PeculiarVentures/ASN1.js/archive/master.zip

Copied the org folder from PKIjs to the PKCS10 sample directory, copied the org folder from the ASN1js folder into the sample directory and tried the PKCS 10 sample and it worked:

![image](https://cloud.githubusercontent.com/assets/1619279/17646024/0c458c02-616d-11e6-9c93-32e3a1059404.png)

When we release the next major release of PKIjs we will remove these two steps but for now that's how you need to get the samples working.
